#!/usr/bin/env bash
# Generates a .env.test file for CI environments.
# This ensures t3-env validation passes during test runs
# without requiring secrets or real configuration.

set -euo pipefail

ENV_FILE=".env.test"

# Refuse to clobber an existing local file outside CI.
if [ -z "${CI:-}" ] && [ -f "$ENV_FILE" ]; then
  echo "Refusing to overwrite existing $ENV_FILE outside CI." >&2
  echo "Set CI=1 to force, or remove the file manually." >&2
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# Auto-generated by .github/scripts/generate-env-test.sh
# Do not commit this file.

NODE_ENV=test
NEXT_PUBLIC_APP_BASE_URL=http://localhost:3000
EOF

echo "Generated $ENV_FILE"
